USE [GD2C2024]
GO

-- Eliminar constraints
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Venta_Cliente', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Venta DROP CONSTRAINT FK_Venta_Cliente;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Factura_Vendedor', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Factura DROP CONSTRAINT FK_Factura_Vendedor;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Cliente_Usuario', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Cliente DROP CONSTRAINT FK_Cliente_Usuario;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Vendedor_Usuario', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Vendedor DROP CONSTRAINT FK_Vendedor_Usuario;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Domicilio_Localidad', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Domicilio DROP CONSTRAINT FK_Domicilio_Localidad;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Producto', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].AlmacenXProducto DROP CONSTRAINT FK_Producto;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Almacen', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].AlmacenXProducto DROP CONSTRAINT FK_Almacen; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Almacen_publicacion', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Publicacion DROP CONSTRAINT FK_Almacen_publicacion; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_vendedor_publicacion', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Publicacion DROP CONSTRAINT FK_vendedor_publicacion; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Detalle_Factura', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Detalle_Factura DROP CONSTRAINT FK_Detalle_Factura; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Detalle_Publicacion', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Detalle_Factura DROP CONSTRAINT FK_Detalle_Publicacion; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Detalle_Venta', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Detalle_Venta DROP CONSTRAINT FK_Detalle_Venta; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Venta_Publicacion', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Detalle_Venta DROP CONSTRAINT FK_Venta_Publicacion; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Pago_Venta', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Pago DROP CONSTRAINT FK_Pago_Venta; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Detalle_Pago', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Detalle_Pago DROP CONSTRAINT FK_Detalle_Pago; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].Fk_Envio_Domicilio', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Envio DROP CONSTRAINT Fk_Envio_Domicilio;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_Pago_medio', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Detalle_Pago DROP CONSTRAINT FK_Pago_medio; 
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_UsuarioXDomicilio_Usuario', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].UsuarioXDomicilio DROP CONSTRAINT FK_UsuarioXDomicilio_Usuario;
IF OBJECT_ID('[4_FILAS_AFECTADAS].FK_UsuarioXDomicilio_Domicilio', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].UsuarioXDomicilio DROP CONSTRAINT FK_UsuarioXDomicilio_Domicilio;
IF OBJECT_ID('[4_FILAS_AFECTADAS].Fk_Envio_TipoEnvio','F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Envio DROP CONSTRAINT Fk_Envio_TipoEnvio;
IF OBJECT_ID('[4_FILAS_AFECTADAS].Fk_Envio_Venta', 'F') IS NOT NULL ALTER TABLE [4_FILAS_AFECTADAS].Envio DROP CONSTRAINT Fk_Envio_Venta;





-- Eliminar tablas existentes si ya existen
IF OBJECT_ID('4_FILAS_AFECTADAS.Factura', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Factura;
IF OBJECT_ID('4_FILAS_AFECTADAS.Producto', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Producto;
IF OBJECT_ID('4_FILAS_AFECTADAS.Venta', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Venta;
IF OBJECT_ID('4_FILAS_AFECTADAS.Cliente', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Cliente;
IF OBJECT_ID('4_FILAS_AFECTADAS.Vendedor', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Vendedor;
IF OBJECT_ID('4_FILAS_AFECTADAS.Usuario', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Usuario;
IF OBJECT_ID('4_FILAS_AFECTADAS.Almacen', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Almacen;
IF OBJECT_ID('4_FILAS_AFECTADAS.Domicilio', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Domicilio;
IF OBJECT_ID('4_FILAS_AFECTADAS.Localidad', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Localidad;
IF OBJECT_ID('4_FILAS_AFECTADAS.Provincia', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Provincia;
IF OBJECT_ID('4_FILAS_AFECTADAS.SubRubro', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].SubRubro;
IF OBJECT_ID('4_FILAS_AFECTADAS.Rubro', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Rubro;
IF OBJECT_ID('4_FILAS_AFECTADAS.Marca', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Marca;
IF OBJECT_ID('4_FILAS_AFECTADAS.Modelo', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Modelo;
IF OBJECT_ID('4_FILAS_AFECTADAS.MedioDePago', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].MedioDePago;
IF OBJECT_ID('4_FILAS_AFECTADAS.TipoEnvio', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].TipoEnvio;
IF OBJECT_ID('4_FILAS_AFECTADAS.AlmacenXProducto', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].AlmacenXProducto;
IF OBJECT_ID('4_FILAS_AFECTADAS.Publicacion', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Publicacion;
IF OBJECT_ID('4_FILAS_AFECTADAS.Detalle_Factura', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Detalle_Factura;
IF OBJECT_ID('4_FILAS_AFECTADAS.Detalle_Venta', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Detalle_Venta;
IF OBJECT_ID('4_FILAS_AFECTADAS.Pago', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Pago;
IF OBJECT_ID('4_FILAS_AFECTADAS.Detalle_Pago', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Detalle_Pago;
IF OBJECT_ID('4_FILAS_AFECTADAS.UsuarioXDomicilio', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].UsuarioXDomicilio;
IF OBJECT_ID('4_FILAS_AFECTADAS.Envio', 'U') IS NOT NULL DROP TABLE [4_FILAS_AFECTADAS].Envio;

	DROP PROCEDURE [4_FILAS_AFECTADAS].CARGAR_TABLAS
-- Eliminar esquema si ya existe
IF EXISTS (SELECT * FROM sys.schemas WHERE name = '4_FILAS_AFECTADAS')
BEGIN
    DROP SCHEMA [4_FILAS_AFECTADAS];
END
GO
